# Generated by Django 3.1.6 on 2021-02-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(blank=True, default='', max_length=100)),
                ('diagnosis_code', models.CharField(blank=True, default='', max_length=100)),
                ('full_code', models.CharField(blank=True, default='', max_length=100)),
                ('ab_description', models.CharField(blank=True, default='', max_length=250)),
                ('full_description', models.CharField(blank=True, default='', max_length=250)),
                ('category_title', models.CharField(blank=True, default='', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ICD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.icd')),
            ],
        ),
    ]
