# Generated by Django 3.1.6 on 2021-02-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='ICD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codes', to='codes.icd'),
        ),
    ]
