# Generated by Django 3.1.6 on 2021-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20210207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='diagnosis_code',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='full_code',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
