# Generated by Django 3.1.6 on 2021-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20210208_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='diagnosis_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
