# Generated by Django 3.1.6 on 2021-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20210209_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='full_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
